# general
name: SwinIRSmall
model_type: SRGANModel
scale: 1
num_gpu: auto
manual_seed: 0

# USM the ground-truth #if these are true, it will apply an unsharp mask to the HR images, causing halos on the output
l1_gt_usm: True
percep_gt_usm: True
gan_gt_usm: False

# dataset and data loader
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt:  # TODO: Put Path to Ground-truth/High-resolution images here
    dataroot_lq:  # TODO: Put Path to Low-quality/Low-resolution images here
    # meta_info_file: basicsr/data/meta_info/meta_info_DIV2K800sub_GT.txt
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 48  # Crop Npx square from your images, larger is usually better but uses more VRAM
    use_hflip: true  # Flip the images horizontally at random intervals
    use_rot: true  # Rotate the images at random angles

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

# network structures
network_g:
  type: SwinIR
  upscale: 1
  in_chans: 3
  img_size: 48  # should be `gt_size/scale`, e.g., if gt_size=128 and scale=4, img_size should be 32
  window_size: 8
  img_range: 1.
  depths: [6, 6, 6, 6]
  embed_dim: 60
  num_heads: [6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: ~  # optional base/parent generator network
  strict_load_g: true
  resume_state: ~  # optional training `.state` file to resume from

# training
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [200000, 400000]  # reduce learning rate at these iterations
    gamma: 0.5

  total_iter: 400000
  warmup_iter: -1  # no warm up

  # Pixel Loss (minimizes pixel-wise difference)
  pixel_opt:
    type: L1Loss
    loss_weight: 0.8
    reduction: mean

  # Perceptual Loss (aligns with perceptual similarity)
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      # before relu
      "conv1_2": 0.1
      "conv2_2": 0.1
      "conv3_4": 2
      "conv4_4": 2
      "conv5_4": 2
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: !!float 1.0
    style_weight: 0
    range_norm: false
    criterion: l1

  # Contextual Loss (compares features)
  contextual_opt:
    type: ContextualLoss
    layer_weights:
      "conv_3_2": 0.15
      "conv_4_2": 0.15
    max_1d_size: 64
    distance_type: "cosine"
    calc_type: "regular"
    z_norm: false
    crop_quarter: false,
    b: 1.0
    band_width: 0.5
    use_vgg: true,
    net: vgg19

  # Color Loss (aligns with color distribution)
  color_opt:
    type: ColorLoss
    criterion: "l1"
    loss_weight: 1

  # GAN Loss (trains generator to fool discriminator)
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 1e-1

# logging
logger:
  print_freq: 100
  save_checkpoint_freq: 800
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training
dist_params:
  backend: nccl
  port: 29500
